apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
    # alternative (helper): include "postgres.labels" .

spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
    # alternative (helper): include "postgres.selectorLabels" .
